version: "3.1"

services:

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    restart: on-failure
    ports:
      - '5672:5672'
    networks:
      - my-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: on-failure
    ports:
      - '9411:9411'
    networks:
      - my-network

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - my-network


  
  
  mysql:
    container_name: mysql-container
    image: mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: employee_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql_data_pub:/var/lib/mysql
    networks:
      - my-network





  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    restart: on-failure
    ports:
      - '9191:9191'
    depends_on:
      - service-registry
    environment:
      - SPRING_APPLICATION_NAME=API-GATEWAY
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/



    networks:
      - my-network

  config-server:
    container_name: config-server
    build: ./config-server
    restart: on-failure
    ports:
      - '8887:8887'
    environment:
      - SPRING_APPLICATION_NAME=CONFIG-SERVER
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/kissmylala/config-server-repo
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START:"true"

    networks:
      - my-network


  service-registry:
    container_name: service-registry
    build: ./service-registry
    restart: on-failure
    ports:
        - '8761:8761'
    networks:
      - my-network


  employee-service:
    container_name: employee-service
    restart: on-failure
    build: ./employee-service
    ports:
      - '8081:8081'
    depends_on:
      - mysql
      - rabbitmq
      - service-registry
      - config-server

    environment:
      - SPRING_APPLICATION_NAME=EMPLOYEE-SERVICE
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8887

    networks:
      - my-network

  department-service:
    container_name: department-service
    restart: always
    build: ./department-service
    ports:
      - '8084:8084'
    depends_on:
      - mysql
      - rabbitmq
      - service-registry
      - config-server
    environment:
      - SPRING_APPLICATION_NAME=DEPARTMENT-SERVICE
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8887

    networks:
      - my-network


  organization-service:
    container_name: organization-service
    restart: on-failure
    build: ./organization-service
    ports:
      - '8083:8083'
    depends_on:
      - mysql
      - rabbitmq
      - service-registry
      - config-server
    environment:
      - SPRING_APPLICATION_NAME=ORGANIZATION-SERVICE
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8887


    networks:
      - my-network

networks:
  my-network:

volumes:
  mysql_data_pub:




